# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ZYNQ_CORE_ila_0_1.xci
# IP: The module: 'ZYNQ_CORE_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ZYNQ_CORE_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ZYNQ_CORE_ila_0_1.xci
# IP: The module: 'ZYNQ_CORE_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ZYNQ_CORE_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
