# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_blk_mem_gen_0_2/ZYNQ_CORE_blk_mem_gen_0_2.xci
# IP: The module: 'ZYNQ_CORE_blk_mem_gen_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_blk_mem_gen_0_2/ZYNQ_CORE_blk_mem_gen_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_blk_mem_gen_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_blk_mem_gen_0_2/ZYNQ_CORE_blk_mem_gen_0_2.xci
# IP: The module: 'ZYNQ_CORE_blk_mem_gen_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_blk_mem_gen_0_2/ZYNQ_CORE_blk_mem_gen_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_blk_mem_gen_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
