# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/HDMI_XDC.xdc

# Block Designs: bd/HDMI/HDMI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI || ORIG_REF_NAME==HDMI} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_clk_wiz_0_0/HDMI_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_clk_wiz_0_0 || ORIG_REF_NAME==HDMI_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_color_bar_0_0/HDMI_color_bar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_color_bar_0_0 || ORIG_REF_NAME==HDMI_color_bar_0_0} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_rgb2dvi_0_1/HDMI_rgb2dvi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_rgb2dvi_0_1 || ORIG_REF_NAME==HDMI_rgb2dvi_0_1} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_xlconstant_0_0/HDMI_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_xlconstant_0_0 || ORIG_REF_NAME==HDMI_xlconstant_0_0} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_xlconcat_0_0/HDMI_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_xlconcat_0_0 || ORIG_REF_NAME==HDMI_xlconcat_0_0} -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PL_HDMI/PL_HDMI.gen/sources_1/bd/HDMI/HDMI_ooc.xdc
