# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PS_TIMER_XDC.xdc

# Block Designs: bd/ZYNQ_CORE/ZYNQ_CORE.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE || ORIG_REF_NAME==ZYNQ_CORE} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_processing_system7_0_0/ZYNQ_CORE_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_CORE_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_ila_0_1/ZYNQ_CORE_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_ila_0_1 || ORIG_REF_NAME==ZYNQ_CORE_ila_0_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xlslice_0_0/ZYNQ_CORE_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xlslice_0_0 || ORIG_REF_NAME==ZYNQ_CORE_xlslice_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xlslice_1_0/ZYNQ_CORE_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xlslice_1_0 || ORIG_REF_NAME==ZYNQ_CORE_xlslice_1_0} -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_TIMER/prj/xilinx/PS_TIMER.gen/sources_1/bd/ZYNQ_CORE/ZYNQ_CORE_ooc.xdc
