# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Programs/Workspace/SmartZYNQ_SP2/VDMA_OV5640_HDMI_with_customIP/VDMA_OV5640_HDMI_with_customIP.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_tc_0_0/ZYNQ_CORE_v_tc_0_0.xci
# IP: The module: 'ZYNQ_CORE_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/VDMA_OV5640_HDMI_with_customIP/VDMA_OV5640_HDMI_with_customIP.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_tc_0_0/ZYNQ_CORE_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/VDMA_OV5640_HDMI_with_customIP/VDMA_OV5640_HDMI_with_customIP.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_tc_0_0/ZYNQ_CORE_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Programs/Workspace/SmartZYNQ_SP2/VDMA_OV5640_HDMI_with_customIP/VDMA_OV5640_HDMI_with_customIP.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_tc_0_0/ZYNQ_CORE_v_tc_0_0.xci
# IP: The module: 'ZYNQ_CORE_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/VDMA_OV5640_HDMI_with_customIP/VDMA_OV5640_HDMI_with_customIP.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_tc_0_0/ZYNQ_CORE_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/VDMA_OV5640_HDMI_with_customIP/VDMA_OV5640_HDMI_with_customIP.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_tc_0_0/ZYNQ_CORE_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
