set_property IOSTANDARD LVCMOS33 [get_ports clk_out1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out2]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out3]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out4]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]

set_property PACKAGE_PIN M19 [get_ports clk]
set_property PACKAGE_PIN H19 [get_ports clk_out1]
set_property PACKAGE_PIN E18 [get_ports clk_out2]
set_property PACKAGE_PIN F18 [get_ports clk_out3]
set_property PACKAGE_PIN E19 [get_ports clk_out4]
set_property PACKAGE_PIN P20 [get_ports led1]
set_property PACKAGE_PIN P21 [get_ports led2]