# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_EMIO_KEY/prj/xilinx/template.srcs/sources_1/bd/EMIO_KEY/ip/EMIO_KEY_processing_system7_0_0/EMIO_KEY_processing_system7_0_0.xci
# IP: The module: 'EMIO_KEY_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_EMIO_KEY/prj/xilinx/template.gen/sources_1/bd/EMIO_KEY/ip/EMIO_KEY_processing_system7_0_0/EMIO_KEY_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMIO_KEY_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_EMIO_KEY/prj/xilinx/template.srcs/sources_1/bd/EMIO_KEY/ip/EMIO_KEY_processing_system7_0_0/EMIO_KEY_processing_system7_0_0.xci
# IP: The module: 'EMIO_KEY_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_EMIO_KEY/prj/xilinx/template.gen/sources_1/bd/EMIO_KEY/ip/EMIO_KEY_processing_system7_0_0/EMIO_KEY_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMIO_KEY_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
