# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PIN.xdc

# Block Designs: bd/ZYNQ_CORE/ZYNQ_CORE.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE || ORIG_REF_NAME==ZYNQ_CORE} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_processing_system7_0_1/ZYNQ_CORE_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_processing_system7_0_1 || ORIG_REF_NAME==ZYNQ_CORE_processing_system7_0_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_bram_ctrl_0_4/ZYNQ_CORE_axi_bram_ctrl_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_bram_ctrl_0_4 || ORIG_REF_NAME==ZYNQ_CORE_axi_bram_ctrl_0_4} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_bram_ctrl_0_5/ZYNQ_CORE_axi_bram_ctrl_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_bram_ctrl_0_5 || ORIG_REF_NAME==ZYNQ_CORE_axi_bram_ctrl_0_5} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_bram_ctrl_0_6/ZYNQ_CORE_axi_bram_ctrl_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_bram_ctrl_0_6 || ORIG_REF_NAME==ZYNQ_CORE_axi_bram_ctrl_0_6} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_blk_mem_gen_0_2/ZYNQ_CORE_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_blk_mem_gen_0_2 || ORIG_REF_NAME==ZYNQ_CORE_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_blk_mem_gen_0_3/ZYNQ_CORE_blk_mem_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_blk_mem_gen_0_3 || ORIG_REF_NAME==ZYNQ_CORE_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/ZYNQ_CORE_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_smc_1 || ORIG_REF_NAME==ZYNQ_CORE_axi_smc_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_50M_1/ZYNQ_CORE_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_1 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_1} -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ZYNQ_CORE_ooc.xdc
