# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/EMIO_KEY_XDC.xdc

# Block Designs: bd/EMIO_KEY/EMIO_KEY.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EMIO_KEY || ORIG_REF_NAME==EMIO_KEY} -quiet] -quiet

# IP: bd/EMIO_KEY/ip/EMIO_KEY_processing_system7_0_0/EMIO_KEY_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EMIO_KEY_processing_system7_0_0 || ORIG_REF_NAME==EMIO_KEY_processing_system7_0_0} -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_EMIO_KEY/prj/xilinx/template.gen/sources_1/bd/EMIO_KEY/EMIO_KEY_ooc.xdc
