set_property SRC_FILE_INFO {cfile:D:/Programs/Workspace/SmartZYNQ_SP2/Vitis_test/Vitis_test.srcs/constrs_1/new/LED_TEST.xdc rfile:../../../Vitis_test.srcs/constrs_1/new/LED_TEST.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports GPIO_0_0_tri_io[0]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P21 [get_ports GPIO_0_0_tri_io[1]]
