# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/HDMI.xdc

# Block Designs: bd/HDMI/HDMI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI || ORIG_REF_NAME==HDMI} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_DVI_Transmitter_0_0/HDMI_DVI_Transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_DVI_Transmitter_0_0 || ORIG_REF_NAME==HDMI_DVI_Transmitter_0_0} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_clk_wiz_0_0/HDMI_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_clk_wiz_0_0 || ORIG_REF_NAME==HDMI_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_vga_ctrl_0_0/HDMI_vga_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_vga_ctrl_0_0 || ORIG_REF_NAME==HDMI_vga_ctrl_0_0} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_vga_pic_0_0/HDMI_vga_pic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_vga_pic_0_0 || ORIG_REF_NAME==HDMI_vga_pic_0_0} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_util_vector_logic_0_0/HDMI_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_util_vector_logic_0_0 || ORIG_REF_NAME==HDMI_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/HDMI/ip/HDMI_util_vector_logic_0_1/HDMI_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_util_vector_logic_0_1 || ORIG_REF_NAME==HDMI_util_vector_logic_0_1} -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/HDMI_DRIVER_REL2.0_with_customIP/HDMI_DRIVER_REL2.0.gen/sources_1/bd/HDMI/HDMI_ooc.xdc
