# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/ZYNQ_CORE_axi_smc_1.xci
# IP: The module: 'ZYNQ_CORE_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/bd_aa9e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_0/bd_aa9e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_1/bd_aa9e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_2/bd_aa9e_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_3/bd_aa9e_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_4/bd_aa9e_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_5/bd_aa9e_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_6/bd_aa9e_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_7/bd_aa9e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_8/bd_aa9e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_9/bd_aa9e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_10/bd_aa9e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_11/bd_aa9e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_12/bd_aa9e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_13/bd_aa9e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_14/bd_aa9e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_15/bd_aa9e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_16/bd_aa9e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_17/bd_aa9e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_18/bd_aa9e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_19/bd_aa9e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_20/bd_aa9e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_21/bd_aa9e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_22/bd_aa9e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_23/bd_aa9e_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_24/bd_aa9e_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_25/bd_aa9e_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_26/bd_aa9e_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_27/bd_aa9e_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_28/bd_aa9e_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_29/bd_aa9e_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_30/bd_aa9e_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_31/bd_aa9e_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_32/bd_aa9e_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_33/bd_aa9e_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_34/bd_aa9e_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_35/bd_aa9e_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_36/bd_aa9e_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_1/bd_aa9e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_1/bd_aa9e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_2/bd_aa9e_arsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_3/bd_aa9e_rsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_4/bd_aa9e_awsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_5/bd_aa9e_wsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_6/bd_aa9e_bsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_10/bd_aa9e_s00a2s_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_11/bd_aa9e_sarn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_12/bd_aa9e_srn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_13/bd_aa9e_sawn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_14/bd_aa9e_swn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_15/bd_aa9e_sbn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_16/bd_aa9e_m00s2a_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_17/bd_aa9e_m00arn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_18/bd_aa9e_m00rn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_19/bd_aa9e_m00awn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_20/bd_aa9e_m00wn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_21/bd_aa9e_m00bn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_23/bd_aa9e_m01s2a_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_24/bd_aa9e_m01arn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_25/bd_aa9e_m01rn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_26/bd_aa9e_m01awn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_27/bd_aa9e_m01wn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_28/bd_aa9e_m01bn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_30/bd_aa9e_m02s2a_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_31/bd_aa9e_m02arn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_32/bd_aa9e_m02rn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_33/bd_aa9e_m02awn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_34/bd_aa9e_m02wn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_35/bd_aa9e_m02bn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/ZYNQ_CORE_axi_smc_1.xci
# IP: The module: 'ZYNQ_CORE_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/bd_aa9e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_0/bd_aa9e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_1/bd_aa9e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_2/bd_aa9e_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_3/bd_aa9e_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_4/bd_aa9e_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_5/bd_aa9e_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_6/bd_aa9e_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_7/bd_aa9e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_8/bd_aa9e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_9/bd_aa9e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_10/bd_aa9e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_11/bd_aa9e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_12/bd_aa9e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_13/bd_aa9e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_14/bd_aa9e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_15/bd_aa9e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_16/bd_aa9e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_17/bd_aa9e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_18/bd_aa9e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_19/bd_aa9e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_20/bd_aa9e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_21/bd_aa9e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_22/bd_aa9e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_23/bd_aa9e_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_24/bd_aa9e_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_25/bd_aa9e_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_26/bd_aa9e_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_27/bd_aa9e_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_28/bd_aa9e_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_29/bd_aa9e_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_30/bd_aa9e_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_31/bd_aa9e_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_32/bd_aa9e_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_33/bd_aa9e_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_34/bd_aa9e_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_35/bd_aa9e_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_36/bd_aa9e_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_1/bd_aa9e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_1/bd_aa9e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_2/bd_aa9e_arsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_3/bd_aa9e_rsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_4/bd_aa9e_awsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_5/bd_aa9e_wsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_6/bd_aa9e_bsw_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_10/bd_aa9e_s00a2s_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_11/bd_aa9e_sarn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_12/bd_aa9e_srn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_13/bd_aa9e_sawn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_14/bd_aa9e_swn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_15/bd_aa9e_sbn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_16/bd_aa9e_m00s2a_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_17/bd_aa9e_m00arn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_18/bd_aa9e_m00rn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_19/bd_aa9e_m00awn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_20/bd_aa9e_m00wn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_21/bd_aa9e_m00bn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_23/bd_aa9e_m01s2a_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_24/bd_aa9e_m01arn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_25/bd_aa9e_m01rn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_26/bd_aa9e_m01awn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_27/bd_aa9e_m01wn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_28/bd_aa9e_m01bn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_30/bd_aa9e_m02s2a_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_31/bd_aa9e_m02arn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_32/bd_aa9e_m02rn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_33/bd_aa9e_m02awn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_34/bd_aa9e_m02wn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/bd_0/ip/ip_35/bd_aa9e_m02bn_0_ooc.xdc

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PS_BRAM/PS_BRAM.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_CORE_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
