# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PIN_XDC.xdc

# Block Designs: bd/ZYNQ_CORE/ZYNQ_CORE.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE || ORIG_REF_NAME==ZYNQ_CORE} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_processing_system7_0_0/ZYNQ_CORE_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_CORE_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_PL_DDR_RW_0_0/ZYNQ_CORE_PL_DDR_RW_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_PL_DDR_RW_0_0 || ORIG_REF_NAME==ZYNQ_CORE_PL_DDR_RW_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_0/ZYNQ_CORE_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_0 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_us_0/ZYNQ_CORE_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_us_0 || ORIG_REF_NAME==ZYNQ_CORE_auto_us_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_mem_intercon_0/ZYNQ_CORE_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_mem_intercon_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_50M_0/ZYNQ_CORE_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_util_vector_logic_0_0/ZYNQ_CORE_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_util_vector_logic_0_0 || ORIG_REF_NAME==ZYNQ_CORE_util_vector_logic_0_0} -quiet] -quiet

# XDC: d:/Programs/Workspace/SmartZYNQ_SP2/PL_DDR_PS_TEST/PL_DDR_PS_TEST.gen/sources_1/bd/ZYNQ_CORE/ZYNQ_CORE_ooc.xdc
